### PR TITLE
Add auto reconfiguration allowing osx-arm64 builds

### PR DESCRIPTION
**Pull request by FelixMoelder**
As the title says this PR adds auto reconfiguration allowing `osx-arm64` builds.
I would expect this as the final change before starting migration, as local building now passes.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FelixMoelder** [comment]
@conda-forge-admin, please rerender

**Comment by FelixMoelder** [comment]
This should be fine now.

**Comment by ocefpaf** [comment]
LGTM but I'm not an expert on the osx-arm stuff. @isuruf or @xhochy do you mind taking a looking into this one and merging if it is OK?

**Comment by isuruf** [comment]
I don't think you need auto reconfiguration. Only need to copy `config.sub` which is described in the blog post.

**Comment by FelixMoelder** [comment]
> I don't think you need auto reconfiguration. Only need to copy `config.sub` which is described in the blog post.

I tried copying `config.sub` locally. Without reconfiguration building fails returning `Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized`

**Comment by isuruf** [comment]
There must have been some mistake, because copying config.sub is the solution to that exact problem. If you add this package to the migrator list described in the blog post, this will be done automatically for you by the bot.

**Comment by FelixMoelder** [comment]
> There must have been some mistake, because copying config.sub is the solution to that exact problem. If you add this package to the migrator list described in the blog post, this will be done automatically for you by the bot.

Okay, in that case I will add the package as soon as https://github.com/conda-forge/ghostscript-feedstock/pull/16 is running and merged as that is the only remaining requirement for the migration.

**Comment by isuruf** [comment]
The bot will take care of it and migrate the dependencies first, which is the preferred way.

**Comment by FelixMoelder** [comment]
I will close this as the migration will probably do the work here.

**Pull request closed without merging**
