### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
This closes #41, though it disables building for perl in the process.

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
Probably needs a rerender

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Interesting that azure passed, but Travis failed.

**Comment by mariusvniekerk** [comment]
Weird given the error. It seems as if there is some double macro stuff going on under osx

**Comment by ocefpaf** [comment]
> Interesting that azure passed, but Travis failed.

@dpryan79 do you want to try CircleCI for OS X and see if it passes too? (CircleCI is already "standard" in conda-forge and we can merge it is it passes.)

**Comment by ocefpaf** [comment]
CircleCI worked :tada: 

Thanks @dpryan79 and @mariusvniekerk!

**Pull request merged**
